name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'eu.gcr.io/prod-bip/ssb/microdata/data-service'
  repoName: 'prod-bip/ssb/microdata/data-service'
  fullSha: '$(Build.SourceVersion)'
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
  displayName: Use Python 3.9

- script: python -m pip install --upgrade pip
  displayName: 'Install tools'

- script: pip install -r requirements.txt
  displayName: 'Install requirements'

- script: |
    pip install pytest
    pip install pytest-cov
    pytest tests --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html
  displayName: 'Test with pytest'

- task: Docker@2
  displayName: 'Docker build'
  condition: and(succeeded(), eq(variables.isMaster, true))
  inputs:
    repository: $(imageName)
    command: 'build'
    Dockerfile: 'Dockerfile'
    tags: |
      $(Build.SourceBranchName)-$(fullSha)

# Authenticate Docker to GCR using predefined service connection
- task: Docker@2
  displayName: 'Login to GCR'
  condition: and(succeeded(), eq(variables.isMaster, true))
  inputs:
    command: login
    containerRegistry: gcrServiceConnection-Microdatano

# Push Docker Image to GCR
- task: Docker@2
  displayName: 'Push image to GCR'
  condition: and(succeeded(), eq(variables.isMaster, true))
  inputs:
    ContainerRegistry: |
      gcrServiceConnection-Microdatano
    repository: $(repoName)
    command: 'push'
    tags: |
      $(Build.SourceBranchName)-$(fullSha)
