version: 1
formatters:
  simple:
    format: '%(asctime)s - %(threadName)s - %(name)s - %(levelname)s - %(message)r'
  json:
    format: '{"@timestamp":"%(asctime)s","thread_name":"%(threadName)s","logger_name":"%(name)s","level":"%(levelname)s","message":"%(message)r"}'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: json
    stream: ext://sys.stdout
root:
  level: INFO
  handlers: [console]
