name: Run Tests on PR

on:
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python -
        poetry install

    - name: Run tests
      run: poetry run pytest --cov=data_service

  integration-test:
    name: Run Integration test
    runs-on: ubuntu-latest
    needs: test 
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Call workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.INTEGRATION_TEST_PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'statisticsnorway',
              repo: '${{ secrets.INTEGRATION_TEST_REPO }}',
              workflow_id: '${{ secrets.INTEGRATION_TEST_WORKFLOW }}.yaml',
              ref: 'master'
            })
